function myDay(value) {
  var output=document.getElementById("textBox").innerHTML;
  output.innerHTML="";
  document.getElementById("textBox").innerHTML=value;
  var tag = document.createElement("button");
  var text = document.createTextNode("...");
  tag.classList.add("myDayDotButton");
  tag.appendChild(text);
  var element = document.getElementById("textBox");
  element.appendChild(tag);
  var tag = document.createElement("p");
  var text = document.createTextNode("Saturday,October 23");
  tag.classList.add("my-class");
  tag.appendChild(text);
  var element = document.getElementById("textBox");
  element.appendChild(tag);
  var tag = document.createElement("input");
  var text = document.createTextNode("");
  tag.classList.add("taskBox");
  tag.appendChild(text);
  var element = document.getElementById("textBox");
  element.appendChild(tag);
  var tag = document.createElement("button");
  var text = document.createTextNode("ADD");
  tag.classList.add("myDay-AddList");
  tag.appendChild(text);
  var element=document.getElementById("textBox");
  element.appendChild(tag);
  var element = document.getElementsByClassName("myDayDotButton");
  element.onclick = addMyDayListss;
  function addMyDayListss() {
  // let candidate=document.getElementsByClassName("taskBox");
  // let ul=document.getElementById("added-myTask").innerHTML;
  // var li=document.createElement("p");
  // li.setAttribute('id',candidate.value);
  // li.appendChild(document.createTextNode(candidate.value));
  // ul.appendChild(li);
  // console.log(candidate);
  // addMyDayListss();
  let boxInput=document.getElementsByClassName("taskBox");
  let newTask=document.getElementById("added-myTask");
  var listing=document.createElement("p");
  listing.classList.add('new-stylings');
  listing.innerText=boxInput.value;
  newTask.appendChild(listing);
  // boxInput.value="";
}
  // addMyDayListss();
  var elem = document.createElement("div");
  document.body.appendChild(elem);
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
}
function important(value) {
  var output=document.getElementById("textBox").innerHTML;
  output.innerHTML="";
  document.getElementById("textBox").innerHTML=value;
  var tag = document.createElement("button");
  var text = document.createTextNode("...");
  tag.classList.add("myDayDotButton");
  tag.appendChild(text);
  var element = document.getElementById("textBox");
  element.appendChild(tag);
  var tag = document.createElement("input");
  var text = document.createTextNode("");
  tag.classList.add("taskBox");
  tag.appendChild(text);
  var element = document.getElementById("textBox");
  element.appendChild(tag);
  var tag = document.createElement("button");
  var text = document.createTextNode("ADD");
  tag.classList.add("myDay-AddList");
  tag.appendChild(text);
  var element=document.getElementById("textBox");
  element.appendChild(tag);
  var elem = document.createElement("div");
  document.body.appendChild(elem);
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
}
function planned(value) {
  var output=document.getElementById("clickPlan").innerHTML;
  output.innerHTML="";
  document.getElementById("textBox").innerHTML=value;
  var tag = document.createElement("button");
  var text = document.createTextNode("...");
  tag.classList.add("myDayDotButton");
  tag.appendChild(text);
  var element = document.getElementById("textBox");
  element.appendChild(tag);
  var tag = document.createElement("button");
  var text = document.createTextNode("...");
  tag.classList.add("myDayDotButton");
  tag.appendChild(text);
  var element = document.getElementById("textBox");
  element.appendChild(tag);
  var tag = document.createElement("input");
  var text = document.createTextNode("");
  tag.classList.add("taskBox");
  tag.appendChild(text);
  var element = document.getElementById("textBox");
  element.appendChild(tag);
  var tag = document.createElement("button");
  var text = document.createTextNode("ADD");
  tag.classList.add("myDay-AddList");
  tag.appendChild(text);
  var element=document.getElementById("textBox");
  element.appendChild(tag);
  var elem = document.createElement("div");
  document.body.appendChild(elem);
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line"); 
}
function assignedToMe(value) {
  var output=document.getElementById("clickassign").innerHTML;
  output.innerHTML="";
  document.getElementById("textBox").innerHTML=value;
  var tag = document.createElement("button");
  var text = document.createTextNode("...");
  tag.classList.add("myDayDotButton");
  tag.appendChild(text);
  var element = document.getElementById("textBox");
  element.appendChild(tag);
  var tag = document.createElement('img');
  tag.classList.add("assigning-Image");
  tag.src='assets/assign.svg';
  var element = document.getElementById("textBox");
  element.appendChild(tag);
  var tag = document.createElement("div");
  var text = document.createTextNode("Task assigned to you in To Do or Planner show up here");
  tag.classList.add("assign-text");
  tag.appendChild(text);
  var element = document.getElementById("textBox");
  element.appendChild(tag);
}
function tasks(value) {
  var output=document.getElementById("clickTask").innerHTML;
  output.innerHTML="";
  document.getElementById("textBox").innerHTML=value;
  var tag = document.createElement("button");
  var text = document.createTextNode("...");
  tag.classList.add("myDayDotButton");
  tag.appendChild(text);
  var element = document.getElementById("textBox");
  element.appendChild(tag);
  var tag = document.createElement("input");
  var text = document.createTextNode("");
  tag.classList.add("taskBox");
  tag.appendChild(text);
  var element = document.getElementById("textBox");
  element.appendChild(tag);
  var tag = document.createElement("button");
  var text = document.createTextNode("ADD");
  tag.classList.add("myDay-AddList");
  tag.appendChild(text);
  var element=document.getElementById("textBox");
  element.appendChild(tag);
  var elem = document.createElement("div");
  document.body.appendChild(elem);
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
}
function showTask() {
  let boxInput=document.getElementById("new-list");
  let newTask=document.getElementById("added-task");
  var listing=document.createElement("p");
  listing.classList.add('new-styling');
  listing.innerText=boxInput.value;
  newTask.appendChild(listing);
  boxInput.value="";
  let heading=document.getElementsByClassName("leftClick");
  var flow=listing.innerText;
  heading[0].innerHTML=flow;
  listing.addEventListener('click',function() {
  heading[0].innerHTML=listing.innerText;
  var tag = document.createElement("button");
  var text = document.createTextNode("...");
  tag.classList.add("myDayDotButton");
  tag.appendChild(text);
  var element = document.getElementById("textBox");
  element.appendChild(tag);
  var tag = document.createElement("input");
  var text = document.createTextNode("");
  tag.classList.add("taskBox");
  tag.appendChild(text);
  var element = document.getElementById("textBox");
  element.appendChild(tag);
  var tag = document.createElement("button");
  var text = document.createTextNode("ADD");
  tag.classList.add("myDay-AddList");
  tag.appendChild(text);
  var element=document.getElementById("textBox");
  element.appendChild(tag);
  var elem = document.createElement("div");
  document.body.appendChild(elem);
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  var elem = document.createElement("div");
  var element = document.getElementById("textBox");
  element.appendChild(elem);
  elem.classList.add("line");
  })	
}

function hide() {
  var x = document.getElementById("menuBox");
  var y =document.getElementById("leftcollapsed");
  if (x.style.display === "none") {
    x.style.display = "flex";
    y.style.display= "none";
  } else {
    x.style.display = "none";
    y.style.display ="flex";
  }
}
function arrowexpand() {
  var x = document.getElementById("menuBox");
  var y =document.getElementById("leftcollapsed")
  if (y.style.display === "flex") {
    x.style.display = "flex";
    y.style.display= "none";
  } else {
    x.style.display = "none";
    y.style.display ="flex";
  }
}